### ISSUE TITLE
Humble HTTP-Header Security Check

### ISSUE THREAD

**Issue by cyberamt** [CERT-Polska/Artemis-modules-extra#61]
Hi, I have written a module for artemis that uses the [Humble Security Scanner](https://github.com/rfc-st/humble). The module actually only consists of a small command call and an output parser. I would like to contribute the module. What is the best way to do this? Should I fork the project or can you create a branch for me to commit? Best regards :raising_hand_man:

**Comment by kazet** [comment]
Hello,

sorry for the delay in reply and thank you for your interest in contributing to Artemis!

To contribute, fork the repository, create a branch on your fork and create a pull request - Github will understand that this is a pull request to the original repository ;)
